otomasyon ilk cr
taner-kazim/automation-roadmap pull request #1
Opened 2020-12-03 10:11 UTC by taner-kazim

otomasyon ilk cr

2020-12-04 14:34 UTC, busraayaksiz requested changes

2020-12-04 14:34 UTC, busraayaksiz commented on 1-python_fonksiyonlar/3_harfNotu.py
> +
burası okey

2020-12-04 14:34 UTC, busraayaksiz commented on 2-python_classlar/1_insan.py
> +
burası okey eline sağlık

2020-12-04 14:34 UTC, busraayaksiz commented on 2-python_classlar/2_web-push.py
> +
super()__init dosyalarını class initlerinin altına taşıyabilir miyiz?

2020-12-04 14:34 UTC, busraayaksiz commented on 2-python_classlar/2_web-push.py
> +
ödevin içinde verdiğimiz değişkenlerin tip tanımlamaları classların içinde yapılmalı örneğin, trigger_page: str (triggerpush classının içinde trigger_page değişkeninin string olacağını belirtmiştik)

2020-12-04 14:34 UTC, busraayaksiz commented on 3-python_projesi/net-hesaplama.py
> +
Ogrenci class'ının  init fonksiyonu içinde diğer classtan nesne oluşturulmamalı. Bu iki class birbirinden bağamsız çağırılmalı. öğrenci bilgileri alınıp sonrasında soru bilgileri alınmalı

2020-12-04 14:34 UTC, busraayaksiz commented on 4-assertions_POM/Page-Object-Model.txt
> +
süpersin

2020-12-06 10:11 UTC, taner-kazim commented on 1-python_fonksiyonlar/2_sayiOkuma.py
>  sayiAtama(25)
başa değil aslında en sona eklemek gerekiyor, teşekkürler

2020-12-06 10:13 UTC, taner-kazim commented on 2-python_classlar/2_web-push.py
> +
> super()__init dosyalarını class initlerinin altına taşıyabilir miyiz?

burada şu anda da class initlerin altında, tam anlayamadım

2020-12-06 10:16 UTC, taner-kazim commented on 2-python_classlar/2_web-push.py
> +
> ödevin içinde verdiğimiz değişkenlerin tip tanımlamaları classların içinde yapılmalı örneğin, trigger_page: str (triggerpush classının içinde trigger_page değişkeninin string olacağını belirtmiştik)

ne demek istediğini anlayamadım

2020-12-10 10:53 UTC, busraayaksiz reviewed
Güzel olmul eline sağlık efe baksın bi de 👍

2020-12-25 09:40 UTC, merged